version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node-express-app
hooks:
  BeforeInstall:
    - location: deploy/before-install.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: deploy/after-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/app-start.sh
      runas: root
      timeout: 60